
import javax.swing.JOptionPane;
import java.sql.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author YASH
 */
public class School_Registration extends javax.swing.JFrame {

    /**
     * Creates new form School_Registration
     */
    public School_Registration() {
        initComponents();
jTextField1.setText("");
jTextField2.setText("");
jTextField5.setText("");
jTextField6.setText("");
RBComp.setSelected(false);
RBDef.setSelected(false);
RBEngg.setSelected(false);
RBInfo.setSelected(false);
RBMedia.setSelected(false);
RBMedi.setSelected(false);
RBSci.setSelected(false);
jComboBox2.setSelectedIndex(-1);
OptComm.setSelectedIndex(-1);
OptComp.setSelectedIndex(-1);
OptDef.setSelectedIndex(-1);
OptEngg.setSelectedIndex(-1);
OptInfo.setSelectedIndex(-1);
OptMedia.setSelectedIndex(-1);
OptMedi.setSelectedIndex(-1);
OptSci.setSelectedIndex(-1);
OptComm.setEnabled(false);
OptComp.setEnabled(false);
OptDef.setEnabled(false);
OptEngg.setEnabled(false);
OptInfo.setEnabled(false);
OptMedia.setEnabled(false);
OptMedi.setEnabled(false);
OptSci.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        OptSci = new javax.swing.JComboBox<>();
        OptMedi = new javax.swing.JComboBox<>();
        RBMedi = new javax.swing.JRadioButton();
        RBSci = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        OptComm = new javax.swing.JComboBox<>();
        OptComp = new javax.swing.JComboBox<>();
        RBComm = new javax.swing.JRadioButton();
        RBComp = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        OptInfo = new javax.swing.JComboBox<>();
        OptMedia = new javax.swing.JComboBox<>();
        RBInfo = new javax.swing.JRadioButton();
        RBMedia = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        OptDef = new javax.swing.JComboBox<>();
        OptEngg = new javax.swing.JComboBox<>();
        RBDef = new javax.swing.JRadioButton();
        RBEngg = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton1.setText("Cancel And Back to Main Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("<html><body><u>SCHOOL REGISTRATION</u></body</html>");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Light ITC", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel2.setText("Name of School*");

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel3.setText("Address*");

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel4.setText("Type Of Board*");

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel6.setText("Email ID*");

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jLabel9.setText("Phone No.*");

        jTextField1.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        jComboBox2.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CBSE", "RBSE", "ICSE" }));

        jTextField2.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        jTextField5.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        jTextField6.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(115, 115, 115)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Eras Light ITC", 1, 14)); // NOI18N
        jLabel16.setText("Note:- \"*\" marked field should be compulsarily filled. ");

        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton3.setText("Save & Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jButton2.setText("Clear All Entries");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area of Interest for the session", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Light ITC", 1, 14))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Session 4", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 12))); // NOI18N

        OptSci.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptSci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acturial Science", "Genetic Science", "Nuclear Science" }));
        OptSci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptSciActionPerformed(evt);
            }
        });

        OptMedi.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptMedi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pharmacy", "Physiotherapy", "Rehabilitation" }));
        OptMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptMediActionPerformed(evt);
            }
        });

        buttonGroup4.add(RBMedi);
        RBMedi.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBMedi.setText("Medical");
        RBMedi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMediActionPerformed(evt);
            }
        });

        buttonGroup4.add(RBSci);
        RBSci.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBSci.setText("Sciences");
        RBSci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(RBMedi)
                .addGap(138, 138, 138)
                .addComponent(OptMedi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RBSci)
                .addGap(138, 138, 138)
                .addComponent(OptSci, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptSci, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBMedi)
                    .addComponent(RBSci)
                    .addComponent(OptMedi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Session 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 12))); // NOI18N

        OptComm.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptComm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CA", "CS", "Entrepreneurship" }));
        OptComm.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                OptCommPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        OptComp.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CAT", "Civil Services", "CLAT" }));

        buttonGroup1.add(RBComm);
        RBComm.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBComm.setText("Commerce");
        RBComm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCommActionPerformed(evt);
            }
        });

        buttonGroup1.add(RBComp);
        RBComp.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBComp.setText("Competitive Exams");
        RBComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBCompActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(RBComm)
                .addGap(120, 120, 120)
                .addComponent(OptComm, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RBComp)
                .addGap(78, 78, 78)
                .addComponent(OptComp, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptComm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBComm)
                    .addComponent(RBComp))
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Session 3", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 12))); // NOI18N

        OptInfo.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptInfo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cyber Law", "Multimedia", "Networking" }));

        OptMedia.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptMedia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Advertising", "Anchoring", "Photography" }));

        buttonGroup3.add(RBInfo);
        RBInfo.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBInfo.setText("Info. Technology");
        RBInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBInfoActionPerformed(evt);
            }
        });

        buttonGroup3.add(RBMedia);
        RBMedia.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBMedia.setText("Media");
        RBMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBMediaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(RBInfo)
                .addGap(84, 84, 84)
                .addComponent(OptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RBMedia)
                .addGap(150, 150, 150)
                .addComponent(OptMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptMedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBInfo)
                    .addComponent(RBMedia)))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Session 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Eras Demi ITC", 0, 12))); // NOI18N

        OptDef.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptDef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aviation", "Merchant Navy", "NDA" }));

        OptEngg.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        OptEngg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automobile Engg.", "Electrical Engg.", "Mechanical Engg." }));
        OptEngg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptEnggActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBDef);
        RBDef.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBDef.setText("Defence Services");
        RBDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDefActionPerformed(evt);
            }
        });

        buttonGroup2.add(RBEngg);
        RBEngg.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        RBEngg.setText("Engineering");
        RBEngg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEnggActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(RBDef)
                .addGap(87, 87, 87)
                .addComponent(OptDef, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RBEngg)
                .addGap(115, 115, 115)
                .addComponent(OptEngg, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 1, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OptDef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptEngg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBDef)
                    .addComponent(RBEngg)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(524, 524, 524)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1)
                        .addGap(245, 245, 245)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 351, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(30, 30, 30))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Menu_Bar obj= new Menu_Bar();
obj.setVisible(true);
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if((RBComm.isSelected() || RBComp.isSelected()) && (RBDef.isSelected() || RBEngg.isSelected()) && (RBInfo.isSelected() || RBMedia.isSelected()) && (RBMedi.isSelected() || RBSci.isSelected()) && jTextField1.getText().length()!=0 && jTextField2.getText().length()!=0 && jTextField5.getText().length()==7 && jTextField6.getText().length()!=0 && jComboBox2.getSelectedIndex()!=-1)
{String SchoolName, Address, Type_of_Board, EmailID, PhoneNo, Session1="NULL", Session2="NULL", Session3="NULL", Session4="NULL";
SchoolName= jTextField1.getText();
Address= jTextField6.getText();
Type_of_Board= jComboBox2.getSelectedItem().toString();
EmailID= jTextField2.getText();
PhoneNo= jTextField5.getText();
{if(RBComm.isSelected())
{if(OptComm.getSelectedItem()=="CA")
    Session1="Comm - CA";
else if(OptComm.getSelectedItem()=="CS")
    Session1="Comm - CS";
else if(OptComm.getSelectedItem()=="Entrepreneurship")
    Session1="Comm - Entrepreneurship";
}
else if(RBComp.isSelected())
{if(OptComp.getSelectedItem()=="CAT")
    Session1="Comp - CAT";
else if(OptComp.getSelectedItem()=="Civil Services")
    Session1="Comp - Civil Services";
else if(OptComp.getSelectedItem()=="CLAT")
    Session1="Comp - CLAT";
}
}
{if(RBDef.isSelected())
{if(OptDef.getSelectedItem()=="Aviation")
    Session2="Def - Aviation";
else if(OptDef.getSelectedItem()=="Merchant Navy")
    Session2="Def - Merchant Navy";
else if(OptDef.getSelectedItem()=="NDA")
    Session2="Def - NDA";
}
else if(RBEngg.isSelected())
{if(OptEngg.getSelectedItem()=="Automobile Engg.")
    Session2="Engg - Automobile Engg.";
else if(OptEngg.getSelectedItem()=="Electrical Engg.")
    Session2="Engg - Electrical Engg.";
else if(OptEngg.getSelectedItem()=="Mechanical Engg.")
    Session2="Engg - Mechanical Engg.";
}
}
{if(RBInfo.isSelected())
{if(OptInfo.getSelectedItem()=="Cyber Law")
    Session3="Info - Cyber Law";
else if(OptInfo.getSelectedItem()=="Multimedia")
    Session3="Info - Multmedia";
else if(OptInfo.getSelectedItem()=="Networking")
    Session3="Info - Networking";
}
else if(RBMedia.isSelected())
{if(OptMedia.getSelectedItem()=="Advertising")
    Session3="Media - Advertising";
else if(OptMedia.getSelectedItem()=="Anchoring")
    Session3="Media - Anchoring";
else if(OptMedia.getSelectedItem()=="Photography")
    Session3="Media - Photography";
}
}
{if(RBMedi.isSelected())
{if(OptMedi.getSelectedItem()=="Pharmacy")
    Session4="Medi - Pharmacy";
else if(OptMedi.getSelectedItem()=="Physiotherapy")
    Session4="Medi - Physiotherapy";
else if(OptMedi.getSelectedItem()=="Rehabilitation")
    Session4="Medi - Rehabilitation";
}
else if(RBSci.isSelected())
{if(OptSci.getSelectedItem()=="Acturial Science")
    Session4="Sci - Acturial Science";
else if(OptSci.getSelectedItem()=="Genetic Science")
    Session4="Sci - Genetic Science";
else if(OptSci.getSelectedItem()=="Nuclear Science")
    Session4="Sci - Nuclear Science";
}
}
try{
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/EDUFAIR_REGISTRATION_WINDOW","root","rootcap");
    String sql;
    sql="insert into School_Registration values('"+SchoolName+"', '"+Address+"','"+Type_of_Board+"', '"+EmailID+"', '"+PhoneNo+"', '"+Session1+"', '"+Session2+"', '"+Session3+"', '"+Session4+"')";
    Statement st =con.createStatement();
    st.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Entry Registered Successfully");
}
catch(Exception e){JOptionPane.showMessageDialog(null,e.getMessage());}
}
else
    JOptionPane.showMessageDialog(null,"Please Note!!"+"\nIt is compulsory to select any one category in each session."+"\nAlso It is compulsory to fill all the '*' marked fields"+"\nAlso the Phone No. shoul be exactly 7 digits long.");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
jTextField1.setText("");
jTextField2.setText("");
jTextField5.setText("");
jTextField6.setText("");
RBComm.setSelected(false);
RBComp.setSelected(false);
RBDef.setSelected(false);
RBEngg.setSelected(false);
RBInfo.setSelected(false);
RBMedia.setSelected(false);
RBMedi.setSelected(false);
RBSci.setSelected(false);
jComboBox2.setSelectedIndex(-1);
OptComm.setSelectedIndex(-1);
OptComp.setSelectedIndex(-1);
OptDef.setSelectedIndex(-1);
OptEngg.setSelectedIndex(-1);
OptInfo.setSelectedIndex(-1);
OptMedia.setSelectedIndex(-1);
OptMedi.setSelectedIndex(-1);
OptSci.setSelectedIndex(-1);
OptComm.setEnabled(false);
OptComp.setEnabled(false);
OptDef.setEnabled(false);
OptEngg.setEnabled(false);
OptInfo.setEnabled(false);
OptMedia.setEnabled(false);
OptMedi.setEnabled(false);
OptSci.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void OptSciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptSciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptSciActionPerformed

    private void OptMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptMediActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptMediActionPerformed

    private void RBMediActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMediActionPerformed
OptMedi.setEnabled(true);
OptSci.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBMediActionPerformed

    private void RBSciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSciActionPerformed
OptSci.setEnabled(true);
OptMedi.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBSciActionPerformed

    private void OptCommPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_OptCommPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_OptCommPopupMenuWillBecomeInvisible

    private void RBCommActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCommActionPerformed
OptComm.setEnabled(true);
OptComp.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBCommActionPerformed

    private void RBCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBCompActionPerformed
OptComp.setEnabled(true);
OptComm.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBCompActionPerformed

    private void RBInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBInfoActionPerformed
OptInfo.setEnabled(true);
OptMedia.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBInfoActionPerformed

    private void RBMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBMediaActionPerformed
OptMedia.setEnabled(true);
OptInfo.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBMediaActionPerformed

    private void OptEnggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptEnggActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptEnggActionPerformed

    private void RBDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDefActionPerformed
OptDef.setEnabled(true);
OptEngg.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBDefActionPerformed

    private void RBEnggActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEnggActionPerformed
OptEngg.setEnabled(true);
OptDef.setEnabled(false);// TODO add your handling code here:
    }//GEN-LAST:event_RBEnggActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(School_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(School_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(School_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(School_Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new School_Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> OptComm;
    private javax.swing.JComboBox<String> OptComp;
    private javax.swing.JComboBox<String> OptDef;
    private javax.swing.JComboBox<String> OptEngg;
    private javax.swing.JComboBox<String> OptInfo;
    private javax.swing.JComboBox<String> OptMedi;
    private javax.swing.JComboBox<String> OptMedia;
    private javax.swing.JComboBox<String> OptSci;
    private javax.swing.JRadioButton RBComm;
    private javax.swing.JRadioButton RBComp;
    private javax.swing.JRadioButton RBDef;
    private javax.swing.JRadioButton RBEngg;
    private javax.swing.JRadioButton RBInfo;
    private javax.swing.JRadioButton RBMedi;
    private javax.swing.JRadioButton RBMedia;
    private javax.swing.JRadioButton RBSci;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
